package git

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/cockroachdb/errors"
	"github.com/techquestsdev/git-context/internal/config"
)

// Git handles git config operations.
type Git struct {
	globalConfigPath string
}

// NewGit creates a new Git instance.
func NewGit(globalConfigPath string) *Git {
	return &Git{
		globalConfigPath: globalConfigPath,
	}
}

// BackupConfig creates a backup of the git config, but skips the backup
// when the source is a git-context-generated manifest. The backup exists
// to preserve the user's pre-migration `~/.gitconfig` on the first
// switch after upgrade; once we've taken over the file there's nothing
// useful to back up, and re-backing up would clobber the original.
func (g *Git) BackupConfig(backupPath string) error {
	data, err := os.ReadFile(g.globalConfigPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil // No config to backup
		}

		return errors.Wrap(err, "failed to read git config for backup")
	}

	if bytes.HasPrefix(data, []byte(rootConfigHeader)) {
		return nil // Source is a generated manifest; nothing useful to back up.
	}

	if err := os.WriteFile(backupPath, data, 0o644); err != nil {
		return errors.Wrap(err, "failed to create backup")
	}

	return nil
}

// WriteProfileFile writes a flat key→value git config map to `path` using
// atomic temp-file-and-rename semantics.
//
// Receiver `g` is unused here; the method form is kept for API symmetry
// with WriteRootConfig and Regenerate, which do consume receiver state.
func (g *Git) WriteProfileFile(path string, config map[string]any) error {
	content := buildGitConfig(config)

	return atomicWrite(path, []byte(content))
}

// atomicWrite writes data to a sibling `.tmp` file then renames it into place.
// The rename is atomic with respect to concurrent readers (same-filesystem
// rename(2) on POSIX). It is NOT crash-safe: there is no fsync, so a power
// loss between write and rename can leave a partial file.
func atomicWrite(path string, data []byte) error {
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, data, 0o644); err != nil {
		return errors.Wrap(err, "failed to write temp file")
	}

	if err := os.Rename(tmp, path); err != nil {
		_ = os.Remove(tmp)

		return errors.Wrap(err, "failed to rename temp file into place")
	}

	return nil
}

// rootConfigHeader is emitted at the top of the generated ~/.gitconfig.
// Used both to inform users that the file is managed and (optionally in
// the future) to detect prior generations.
const rootConfigHeader = "# Generated by git-context — do not edit. " +
	"Run `git-context` to manage.\n"

// WriteRootConfig generates the ~/.gitconfig manifest:
//   - a header marker
//   - one unconditional [include] block for `defaultProfilePath`, if set
//   - one [includeIf "gitdir:<path>"] block per (path → profile-file) entry
//
// `assignments` keys are normalized directory paths (with trailing `/`),
// values are absolute paths to per-profile gitconfig files. Blocks are
// emitted in sorted key order so output is deterministic.
//
// If the default is empty AND assignments is empty, no file is written
// (avoids clobbering an existing user-managed ~/.gitconfig before any
// git-context state exists).
//
// All embedded paths are slash-normalized via toGitPath so the output
// is parseable on Windows, where filepath.Join produces backslashes
// that git's config parser rejects in unquoted `path =` values.
func (g *Git) WriteRootConfig(defaultProfilePath string, assignments map[string]string) error {
	if defaultProfilePath == "" && len(assignments) == 0 {
		return g.removeManagedManifest()
	}

	var b strings.Builder

	b.WriteString(rootConfigHeader)
	b.WriteString("\n")

	if defaultProfilePath != "" {
		fmt.Fprintf(&b, "[include]\n\tpath = %s\n\n", toGitPath(defaultProfilePath))
	}

	keys := make([]string, 0, len(assignments))
	for k := range assignments {
		keys = append(keys, k)
	}

	sort.Strings(keys)

	for _, dir := range keys {
		fmt.Fprintf(&b, "[includeIf \"gitdir:%s\"]\n\tpath = %s\n\n",
			toGitPath(dir), toGitPath(assignments[dir]))
	}

	return atomicWrite(g.globalConfigPath, []byte(b.String()))
}

// Regenerate writes one gitconfig file per profile under `profilesDir`,
// then writes the root manifest at `g.globalConfigPath`. Called by every
// mutating command (`switch`, `add` with dirs, `remove`, `dir add/remove`).
//
// Per-profile files use the merged (global + profile) configuration so they
// behave identically to the file `switch` used to write inline.
//
// The root manifest is written by WriteRootConfig and may be a no-op if no
// default profile is set and no directories are assigned.
//
// Failure semantics: writes are not transactional across files. Each
// individual file write is atomic (temp+rename), but if a per-profile write
// fails midway the earlier profile files remain on disk and the root
// manifest is NOT updated — `~/.gitconfig` continues to point at the
// previous set. The next successful Regenerate fully reconciles state.
func (g *Git) Regenerate(cfg *config.Config, profilesDir string) error {
	for name := range cfg.Profiles {
		merged, err := cfg.Merge(name)
		if err != nil {
			return errors.Wrapf(err, "failed to merge profile %q", name)
		}

		path := filepath.Join(profilesDir, name+".gitconfig")
		if err := g.WriteProfileFile(path, profileToFlatConfig(merged)); err != nil {
			return errors.Wrapf(err, "failed to write profile file for %q", name)
		}
	}

	defaultPath := ""
	if cfg.Current != "" {
		defaultPath = filepath.Join(profilesDir, cfg.Current+".gitconfig")
	}

	assignments := make(map[string]string)
	for path, profileName := range cfg.AssignmentMap() {
		assignments[path] = filepath.Join(profilesDir, profileName+".gitconfig")
	}

	return g.WriteRootConfig(defaultPath, assignments)
}

// removeManagedManifest deletes the existing root config only if it is one
// of our generated manifests (identified by the rootConfigHeader prefix).
// This prevents stale includes from lingering after the last profile or
// assignment is removed, while leaving any user-authored ~/.gitconfig
// untouched.
func (g *Git) removeManagedManifest() error {
	data, err := os.ReadFile(g.globalConfigPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}

		return errors.Wrap(err, "failed to read existing git config")
	}

	if !bytes.HasPrefix(data, []byte(rootConfigHeader)) {
		return nil
	}

	if err := os.Remove(g.globalConfigPath); err != nil && !os.IsNotExist(err) {
		return errors.Wrap(err, "failed to remove stale git config manifest")
	}

	return nil
}

// toGitPath converts any backslashes in a filesystem path to forward
// slashes so it can be safely embedded in a git config value. git's
// parser rejects unquoted backslashes in `path =` lines on Windows,
// where filepath.Join produces them. filepath.ToSlash is insufficient
// because it only swaps the OS-specific separator — on POSIX it is a
// no-op and would leave Windows-shaped paths (e.g. produced in tests)
// unconverted.
func toGitPath(p string) string {
	return strings.ReplaceAll(p, `\`, `/`)
}

// profileToFlatConfig converts a Profile struct into the flat dotted-key
// map (`user.name`, `url "...".insteadOf`, etc.) that buildGitConfig
// expects. It is the only flatten implementation in the codebase; the
// pre-refactor cmd-side copy was removed in Task 9.
func profileToFlatConfig(profile *config.Profile) map[string]any {
	out := make(map[string]any)

	if profile.User.Name != "" {
		out["user.name"] = profile.User.Name
	}

	if profile.User.Email != "" {
		out["user.email"] = profile.User.Email
	}

	if profile.User.SigningKey != "" {
		out["user.signingkey"] = profile.User.SigningKey
	}

	for _, url := range profile.URL {
		key := fmt.Sprintf("url \"%s\".insteadOf", url.Pattern)
		out[key] = url.InsteadOf
	}

	for _, section := range config.ConfigSections {
		if sectionMap := profile.GetSection(section); sectionMap != nil {
			flattenInto(out, section, sectionMap)
		}
	}

	return out
}

// flattenInto walks a nested map and writes leaf values keyed by dotted path.
func flattenInto(out map[string]any, prefix string, values map[string]any) {
	for k, v := range values {
		key := prefix + "." + k
		if m, ok := v.(map[string]any); ok {
			flattenInto(out, key, m)
		} else {
			out[key] = v
		}
	}
}

// buildGitConfig builds git config format from a map of key-value pairs.
// It handles both regular dotted notation and quoted subsections.
// Returns a formatted git config string with sections and key-value pairs.
//
//nolint:nestif
func buildGitConfig(config map[string]any) string {
	var content strings.Builder

	sectionMap := make(map[string]map[string]any)

	// Group keys by section
	for key, value := range config {
		// Handle quoted subsections like url."pattern".insteadof
		var section, keyName string

		if strings.Contains(key, "\"") {
			// This is a quoted subsection like url."ssh://git@gitlab.molops.io/".insteadof
			// Extract the section with the quoted part intact
			lastDotIdx := strings.LastIndex(key, ".")
			if lastDotIdx > 0 {
				section = key[:lastDotIdx]
				keyName = key[lastDotIdx+1:]
			} else {
				continue
			}
		} else {
			// Regular dot notation
			parts := strings.Split(key, ".")
			if len(parts) >= 2 {
				section = strings.Join(parts[:len(parts)-1], ".")
				keyName = parts[len(parts)-1]
			} else {
				continue
			}
		}

		if sectionMap[section] == nil {
			sectionMap[section] = make(map[string]any)
		}

		sectionMap[section][keyName] = value
	}

	// Write sections
	for section, values := range sectionMap {
		fmt.Fprintf(&content, "[%s]\n", section)

		for k, v := range values {
			fmt.Fprintf(&content, "\t%s = %v\n", k, v)
		}

		content.WriteString("\n")
	}

	return content.String()
}
